#! /usr/bin/python

import os
import json
import argparse

with open("dotfiles.json") as f:
    dotfiles = json.load(f)

parser = argparse.ArgumentParser()
parser.add_argument("-f", "--force", action="store_true")
args = parser.parse_args()

for src, dest in dotfiles["link"].items():
    if not dest:
        dest = os.path.expanduser("~")

    if os.path.isdir(src):
        for path, subdirs, files in os.walk(src):
            for name in files:
                target = os.path.join(os.path.abspath(path), name)
                link_name = os.path.join(dest, path, name)

                try:
                    os.symlink(target, link_name)
                except FileExistsError:
                    if args.force:
                        os.remove(link_name)
                        os.symlink(target, link_name)
    else:
        target = os.path.abspath(src)
        link_name = os.path.join(dest, src)

        try:
            os.symlink(target, link_name)
        except FileExistsError:
            if args.force:
                os.remove(link_name)
                os.symlink(target, link_name)
